### ISSUE TITLE
Reduce minimum gRPC requirements to 1.49.1

### ISSUE THREAD

**Issue by shogunxu** [chrislupp/Philote-Python#29]
**Is your feature request related to a problem? Please describe.**
As of 0.5.1, Philote-Python requires a minimum gRPC version of 1.62.0. This is a very recent release so libraries that have constraints on latest gRPC version cannot be installed together with Philote-Python. 

**Describe the solution you'd like**
In particular Ray 2.3.1 has a latest allowable gRPC version of 1.49.1. To use Philote and Ray together, I would like Philote to allow gRPC 1.49.1

**Describe alternatives you've considered**
Upgrading Ray to 2.9.1 bumps the newest allowed gRPC version to 1.53.1, but that is still older than the current specification.

**Additional context**

**Comment by chrislupp** [comment]
classifying as bug, as this really shouldn't be the case.
